"""migration

Revision ID: b3c42d2bfea8
Revises: b7c15f51646a
Create Date: 2023-04-29 19:36:14.256951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c42d2bfea8'
down_revision = 'b7c15f51646a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('homepage_viewed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'homepage_viewed')
    # ### end Alembic commands ###
