"""migration

Revision ID: b7c15f51646a
Revises: 00e71138a48e
Create Date: 2023-04-25 14:52:15.412504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c15f51646a'
down_revision = '00e71138a48e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ascesa', sa.Column('progress', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ascesa', 'progress')
    # ### end Alembic commands ###
