"""migration

Revision ID: b9073c68ebf1
Revises: 143443efc378
Create Date: 2023-05-07 20:44:10.208119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9073c68ebf1'
down_revision = '143443efc378'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ascesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_ascesa_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ascesa'))
    )
    op.create_index(op.f('ix_ascesa_id'), 'ascesa', ['id'], unique=False)
    op.add_column('user', sa.Column('homepage_viewed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'homepage_viewed')
    op.drop_index(op.f('ix_ascesa_id'), table_name='ascesa')
    op.drop_table('ascesa')
    # ### end Alembic commands ###
