"""change field author

Revision ID: c575fcc3f85a
Revises: 50b1c18f48f4
Create Date: 2023-04-22 00:53:55.548522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c575fcc3f85a'
down_revision = '50b1c18f48f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ascesa', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('ascesa_author_id_fkey', 'ascesa', type_='foreignkey')
    op.create_foreign_key(None, 'ascesa', 'user', ['user_id'], ['id'])
    op.drop_column('ascesa', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ascesa', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ascesa', type_='foreignkey')
    op.create_foreign_key('ascesa_author_id_fkey', 'ascesa', 'user', ['author_id'], ['id'])
    op.drop_column('ascesa', 'user_id')
    # ### end Alembic commands ###
