"""migration

Revision ID: e1e7deebf6fe
Revises: c575fcc3f85a
Create Date: 2023-04-22 00:59:02.205289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e7deebf6fe'
down_revision = 'c575fcc3f85a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ascesa', sa.Column('started_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ascesa', 'started_at')
    # ### end Alembic commands ###
