name: Bump version

on:
  push:
    branches: [ "main" ]

permissions: write-all

jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.TOKEN }}"
          ref: "${{ github.head_ref }}"
      - name: Install Dependencies
        run: |
          sudo apt install python3.11
          curl -sSL https://install.python-poetry.org | python3.11 -
          cd src/backend
          poetry env use 3.11
          poetry install --only dev
          poetry run cz bump
#      - id: cz
#        name: Create bump and changelog
#        uses: commitizen-tools/commitizen-action@master
#        with:
#          github_token: ${{ secrets.TOKEN }}
#      - name: Print Version
#        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
