name: Deploy

on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: executing remote ssh commands using password
       uses: appleboy/ssh-action@v0.1.10
       with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ${{ secrets.WORK_DIR }}
            git checkout ${{ secrets.MAIN_BRANCH }}
            git pull
