name: CI/CD

on:
  push:
    branches: [ "main" ]


jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: Bump version and create changelog with commitizen
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Bump version
        run: |
          sudo apt install python3.11
          curl -sSL https://install.python-poetry.org | python3.11 -
          cd src/backend
          poetry env use 3.11
          poetry install --only dev
          git config --global user.email "ghbot@github.com"
          git config --global user.name GithubActionBot
          poetry run cz bump
          git push
          git push --tags
          
  build:
    runs-on: ubuntu-latest
    needs: bump_version
    steps:
     - name: Executing remote ssh commands using password
       uses: appleboy/ssh-action@v0.1.10
       env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GH_APP_SECRET: ${{ secrets.GH_APP_SECRET }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
       with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: BACKEND_URL,DATABASE_HOST,DATABASE_NAME,DATABASE_USER,DATABASE_PASSWORD,DATABASE_URL,GH_APP_SECRET,SECRET_KEY
          port: 22
          script: |
            cd ${{ vars.WORK_DIR }}
            git checkout ${{ vars.MAIN_BRANCH }}
            git pull
            cd ${{ vars.BUILD_PATH }}
            docker-compose up --build --force-recreate -d
